Carolina053Peke/OT176

controllers/testimonialController.js, routes/testimonials.js
- Update method deleteTestimonial in controllers
- Add route DELETE /:id in testimonial
- Add routes in app.js depend of `OT176-69`
=> add: method deleteTestimonial and added route endp

middlewares/authenticated.js
- Add middleware for check if user is authenticated
- require service jwt OT176-32
=> OT176-26 added middleware for authenticated users

controllers/newController.js, middlewares/authAdmin.js, middlewares/authOwnership.js, migrations/20220421161006-create-new.js, models/new.js, utils/users.js
- Created ownership in order to check if is the same users as the one sent by params or if it's admin.
=> Ot176 34 middleware de ownership

app.js, controllers/contactController.js, routes/contact.js
- Added Contact Routes file
- Added Contact List endpoint
- Added App.js routing
=> contact endpoint

app.js, routes/contact.js
- Added contact routing.
- Added contact list end point
=> OT176-63-add contact end point and routing

app.js, controllers/contactController.js, migrations/20220429120338-addContactColumns.js, migrations/20220429121610-addContactColumns2.js, routes/backoffice.js, routes/contact.js
- Added backoffice route from App.js
- Added backoffice router
=> Ot176 65 listado de contactos

app.js, controllers/contactController.js, migrations/20220429120338-addContactColumns.js, migrations/20220429121610-addContactColumns2.js, routes/contact.js
- Fix contact model migration 
- Added contact controller
- Imported email function to controller
=> Ot176 64 enviar email de contacto

controllers/newController.js, migrations/20220429190917-add-column-type-news.js, routes/news.js, validations/news.js
=> Ot176 47 endpoint creacion novedades

routes/news.js
=> add router get datail new

config/config.js, controllers/testimonialController.js, middlewares/authenticated.js, middlewares/validate.js, routes/testimonials.js, utils/jwt.js, utils/sendMail.js
- Update camelCase variable names
- Update Eslint suggestions and indentation fix
- Add handle errors in sendMail for errors from sendgrid
=> fix: eslint identation / minor changes

app.js, controllers/slideController.js, routes/slides.js
- Add endpoint GET/slides only admin users
- Add controller for handle slides, return all slides order by field `order asc`
- Update app.js for add new route "/slides"
=> OT176-57 Endpoint list all slides

controllers/userController.js
- Update signup: respond only when sendMail is success
- Update signup: catch error sendmail
=> OT176-31 fixed: send mail welcome

controllers/documentationController.js, controllers/organizationController.js
- Amended merging issues on controllers/documentationController.js (accepted incoming changes)
- Amended merging issues on controllers/organizationController.js (accepted incoming changes)
=> merging issues fix

controllers/slideController.js, routes/slides.js
- Add route GET/slides/:id
- Add function in controller to show details of a slide
=> OT176-58 endpoint details one slide

controllers/slideController.js, routes/slides.js
- Update controller to add delete function
- Update routes to add DELETE/slides/:id
=> OT176-61 endpoint delete slides

controllers/contactController.js, routes/contact.js
- Contact route middleware fix (POST)
- Sendmail fix
=> OT176-64-sendmail fix

controllers/organizationController.js, models/Organization.js, routes/organization.js, validations/organizationValidator.js
- Add slides in organization endpoint
- fixes in routes organization
=> OT176-62 add slides to public endpoint

controllers/testimonialController.js, middlewares/authenticated.js, routes/testimonials.js
- Update: Public GET/ to add paginate results
- Update endpoints only admin
- Update middleware to show correct message error
=> OT176-88 add paginate to testimonials

controllers/documentationController.js, controllers/memberController.js, controllers/userController.js, migrations/20220425184721-create-members.js, routes/categories.js, validations/members.js
- Members migration errors fixed
- Members pagination bug fixed
- ESlint script runned
=> Members pagination bug fixed

app.js, test/testimonials.js
- Add tests for testimonials
- Update file app.js, added route `/activities`
=> OT176-102 test endpoints testimonials

routes/comments.js, seeders/20220512172719-add-users.js
- 20 mock users created.
Please run npx sequelize-cli db:seed:migrate and then npx sequelize-cli db:seed:all
=> Ot176 77 crear seed de usuarios

routes/comments.js
- Added and tested route for listing specific contact.
=> OT176-84-endpoint for listing contacts

test/contacts.js
- Now it'll find password from .env.
=> OT176-100-test-endpoints-contact pass fix

test/news.js
=> Ot176 98 test endpoints news

controllers/newController.js, models/new.js, routes/news.js, validations/news.js
=> Ot176 86 agregar paginacion a novedades

test/testimonials.js
- Add env variables for admin user
- Remove file type check in image field (optional)
=> fixed: image attribute is optional, add env variab

migrations/20220519233513-change-column-type-organization.js
- Column name added
Please run migrations and seeders once again.
=> column name fix

controllers/categoryController.js, controllers/userController.js, models/Organization.js, models/user.js, routes/users.js, seeders/20220521004643-categories.js, seeders/20220521013822-contacts.js, seeders/20220521014000-news.js, seeders/20220521014607-comments.js, seeders/20220521014835-members.js, seeders/20220521014856-organization.js, seeders/20220521014954-slides.js, seeders/20220521015006-testimonials.js, utils/awsImageUploader.js, utils/multer.js
- Image change mandatory on users update changed
- Eslint runned
- deprecated users methods deleted
- awsImageUploader validation for file on request added
=> User image mandatory
